require('dotenv').config();
const fs = require('fs');

const REPORT_URL = process.env.REPORT_URL || 'https://23f3004122.github.io/GTM_intelligence/';

async function postSlackMessage(analysis) {
  const { pipeline_summary, red_flags, next_best_actions = [] } = analysis;

  // Top 3 red flags inline
  const redFlagText = red_flags.slice(0, 3).map(f => {
    const emoji = f.severity === 'high' ? '🔴' : f.severity === 'medium' ? '🟡' : '🟢';
    return `${emoji} *${f.deal_name}* — ${f.explanation}`;
  }).join('\n') || '_No red flags detected ✅_';

  // Top 2 actions inline
  const actionsText = next_best_actions.slice(0, 2).map((a, i) =>
    `${i + 1}. *${a.deal_name}* — ${a.action}`
  ).join('\n') || '_No actions generated_';

  const blocks = [
    // ── Header ──
    {
      type: "header",
      text: { type: "plain_text", text: `🎯 GTM Intelligence — ${new Date().toDateString()}` }
    },

    // ── Pipeline summary ──
    {
      type: "section",
      fields: [
        { type: "mrkdwn", text: `*💰 Total Pipeline*\n$${(pipeline_summary.total_open_pipeline / 1e6).toFixed(1)}M` },
        { type: "mrkdwn", text: `*📈 Weighted Forecast*\n$${(pipeline_summary.weighted_forecast / 1e6).toFixed(1)}M` },
        { type: "mrkdwn", text: `*🚨 Red Flags*\n${red_flags.length} deals need attention` },
        { type: "mrkdwn", text: `*📅 Closing This Month*\n${pipeline_summary.closing_this_month} deals` }
      ]
    },

    { type: "divider" },

    // ── Top red flags ──
    {
      type: "section",
      text: { type: "mrkdwn", text: `*🚨 Top Red Flags*\n${redFlagText}` }
    },

    { type: "divider" },

    // ── Next best actions ──
    {
      type: "section",
      text: { type: "mrkdwn", text: `*⚡ Next Best Actions*\n${actionsText}` }
    },

    { type: "divider" },

    // ── View full report button ──
    {
      type: "actions",
      elements: [
        {
          type: "button",
          text: { type: "plain_text", text: "📊 View Full Report" },
          url: REPORT_URL,
          style: "primary"
        }
      ]
    },

    // ── Footer ──
    {
      type: "context",
      elements: [
        { type: "mrkdwn", text: `🔗 ${REPORT_URL} · Generated by GTM Intelligence · CloudColon` }
      ]
    }
  ];

  const res = await fetch('https://slack.com/api/chat.postMessage', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${process.env.SLACK_BOT_TOKEN}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({ channel: process.env.SLACK_CHANNEL_ID, blocks })
  });

  const data = await res.json();
  if (!data.ok) throw new Error(`Slack postMessage failed: ${data.error}`);
  console.log('✅ Slack message posted');
  return data.ts;
}

async function uploadReportFile(messageTs) {
  const fileContent = fs.readFileSync('output/report.html');
  const fileSize = Buffer.byteLength(fileContent);

  // Step 1: Get upload URL
  const urlRes = await fetch('https://slack.com/api/files.getUploadURLExternal', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${process.env.SLACK_BOT_TOKEN}`,
      'Content-Type': 'application/x-www-form-urlencoded'
    },
    body: new URLSearchParams({
      filename: 'gtm-report.html',
      length: String(fileSize)
    })
  });

  const urlData = await urlRes.json();
  if (!urlData.ok) throw new Error(`files.getUploadURLExternal failed: ${urlData.error}`);

  const { upload_url, file_id } = urlData;

  // Step 2: Upload file content
  const uploadRes = await fetch(upload_url, {
    method: 'POST',
    headers: { 'Content-Type': 'text/html' },
    body: fileContent
  });
  if (!uploadRes.ok) throw new Error(`File upload failed: ${uploadRes.status} ${uploadRes.statusText}`);

  // Step 3: Complete upload and attach to thread
  const completeRes = await fetch('https://slack.com/api/files.completeUploadExternal', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${process.env.SLACK_BOT_TOKEN}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      files: [{ id: file_id }],
      channel_id: process.env.SLACK_CHANNEL_ID,
      thread_ts: messageTs
    })
  });

  const completeData = await completeRes.json();
  if (!completeData.ok) throw new Error(`files.completeUploadExternal failed: ${completeData.error}`);

  console.log('✅ Report file uploaded to thread');
}

async function main() {
  const analysis = JSON.parse(fs.readFileSync('output/analysis.json', 'utf8'));
  const ts = await postSlackMessage(analysis);
  await uploadReportFile(ts);
  console.log('✅ Slack notification sent');
}

main().catch(e => { console.error(e.message); process.exit(1); });